name: secondapp
description: "Fy first flutter sound app"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # libs
  provider: ^6.0.0
  math_expressions: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # data
  assets:
    - assets/sounds/some.mp3

